# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02062be4a5221b70a770d8fbb0bba5177360c9471769f02a137f4d16b31bcd2f8dc2efd956f24234cb2c8260afe497242af31ea00cf993af1a0544e967ffe2a7

test:
  secret_key_base: b2d630d5961b625c0c95884964e84e02a0a52c491fe008d56a66de1141c7580f860f5121d8dbb4b4e8b761ad5a8c9ac8f86913ed6df5060629b48e5df02a5f3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
